[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.production"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = { }

[environments.staging]
variables = { }

# Service configuration
[[services]]
name = "reddit-content-platform-api"
source = "."

[[services]]
name = "reddit-content-platform-worker"
source = "."
startCommand = "celery -A app.core.celery_app worker --loglevel=info --concurrency=2"

[[services]]
name = "reddit-content-platform-scheduler"
source = "."
startCommand = "celery -A app.core.celery_app beat --loglevel=info"