"""Initial migration with all models

Revision ID: 38cc747a2459
Revises: 
Create Date: 2025-07-19 15:51:46.349473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38cc747a2459'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=False),
    sa.Column('oauth_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('keywords',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'keyword', name='uq_user_keyword')
    )
    op.create_index(op.f('ix_keywords_id'), 'keywords', ['id'], unique=False)
    op.create_index(op.f('ix_keywords_user_id'), 'keywords', ['user_id'], unique=False)
    op.create_table('process_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('task_metadata', sa.Text(), nullable=True),
    sa.Column('execution_time_seconds', sa.Integer(), nullable=True),
    sa.Column('memory_usage_mb', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_process_logs_created_at', 'process_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_process_logs_id'), 'process_logs', ['id'], unique=False)
    op.create_index('ix_process_logs_status', 'process_logs', ['status'], unique=False)
    op.create_index('ix_process_logs_task_id', 'process_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_process_logs_user_id'), 'process_logs', ['user_id'], unique=False)
    op.create_index('ix_process_logs_user_task_type', 'process_logs', ['user_id', 'task_type'], unique=False)
    op.create_table('blog_contents',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('template_used', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('featured_image_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_contents_id'), 'blog_contents', ['id'], unique=False)
    op.create_index('ix_blog_contents_keyword_generated', 'blog_contents', ['keyword_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_blog_contents_keyword_id'), 'blog_contents', ['keyword_id'], unique=False)
    op.create_index('ix_blog_contents_slug', 'blog_contents', ['slug'], unique=False)
    op.create_index('ix_blog_contents_status', 'blog_contents', ['status'], unique=False)
    op.create_table('posts',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('reddit_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('subreddit', sa.String(length=255), nullable=False),
    sa.Column('post_created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_created_at', 'posts', ['post_created_at'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_keyword_id'), 'posts', ['keyword_id'], unique=False)
    op.create_index('ix_posts_keyword_score', 'posts', ['keyword_id', 'score'], unique=False)
    op.create_index(op.f('ix_posts_reddit_id'), 'posts', ['reddit_id'], unique=True)
    op.create_index('ix_posts_subreddit', 'posts', ['subreddit'], unique=False)
    op.create_table('comments',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('reddit_id', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment_created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_created_at', 'comments', ['comment_created_at'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index('ix_comments_post_score', 'comments', ['post_id', 'score'], unique=False)
    op.create_index(op.f('ix_comments_reddit_id'), 'comments', ['reddit_id'], unique=True)
    op.create_table('metrics',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('tfidf_score', sa.Float(), nullable=False),
    sa.Column('trend_velocity', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('virality_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_engagement_score', 'metrics', ['engagement_score'], unique=False)
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_index('ix_metrics_post_calculated', 'metrics', ['post_id', 'calculated_at'], unique=False)
    op.create_index(op.f('ix_metrics_post_id'), 'metrics', ['post_id'], unique=False)
    op.create_index('ix_metrics_tfidf_score', 'metrics', ['tfidf_score'], unique=False)
    op.create_index('ix_metrics_trend_velocity', 'metrics', ['trend_velocity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_trend_velocity', table_name='metrics')
    op.drop_index('ix_metrics_tfidf_score', table_name='metrics')
    op.drop_index(op.f('ix_metrics_post_id'), table_name='metrics')
    op.drop_index('ix_metrics_post_calculated', table_name='metrics')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_index('ix_metrics_engagement_score', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_comments_reddit_id'), table_name='comments')
    op.drop_index('ix_comments_post_score', table_name='comments')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index('ix_comments_created_at', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_posts_subreddit', table_name='posts')
    op.drop_index(op.f('ix_posts_reddit_id'), table_name='posts')
    op.drop_index('ix_posts_keyword_score', table_name='posts')
    op.drop_index(op.f('ix_posts_keyword_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index('ix_posts_created_at', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_blog_contents_status', table_name='blog_contents')
    op.drop_index('ix_blog_contents_slug', table_name='blog_contents')
    op.drop_index(op.f('ix_blog_contents_keyword_id'), table_name='blog_contents')
    op.drop_index('ix_blog_contents_keyword_generated', table_name='blog_contents')
    op.drop_index(op.f('ix_blog_contents_id'), table_name='blog_contents')
    op.drop_table('blog_contents')
    op.drop_index('ix_process_logs_user_task_type', table_name='process_logs')
    op.drop_index(op.f('ix_process_logs_user_id'), table_name='process_logs')
    op.drop_index('ix_process_logs_task_id', table_name='process_logs')
    op.drop_index('ix_process_logs_status', table_name='process_logs')
    op.drop_index(op.f('ix_process_logs_id'), table_name='process_logs')
    op.drop_index('ix_process_logs_created_at', table_name='process_logs')
    op.drop_table('process_logs')
    op.drop_index(op.f('ix_keywords_user_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
